[dlg ModMenuName]
Amicitia Mod Menu[w][e]

[sel ModMenu]
[s]Check Phone/Auto Recover[f 4 26 0 93][e]
[s]Player[f 4 26 1 94][e]
[s]Battle Select[f 4 26 2 95][e]
[s]Teleport[f 4 26 3 96][e]
[s]Sound Test[f 4 26 4 97][e]
[s]Field Select[f 4 26 5 98][e]
[s]Event Select[f 4 26 6 99][e]
[s]Camera[f 4 26 7 100][e]
[s]NPCs[f 4 26 8 101][e]
[s]Flags[f 4 26 9 102][e]
[s]Calendar[f 4 26 10 103][e]
[s]Cutin Test[f 4 26 11 104][e]
[s]Font Test[f 4 26 12 105][e]
[s]Particle Test[f 4 26 13 106][e]
[s]Edit Environment[f 4 26 14 107][e]
[s]Shop Test[f 4 26 15 108][e]
[s]Text Chat Test[f 4 26 16 109][e]
[s]About[f 4 26 17 110][e]

[dlg GENERIC_HELP_93]
[s]View your IM messages[n]or auto heal the party[n]just like the Square Button is[n]supposed to do.[e]

[dlg GENERIC_HELP_94]
[s]Edit your Personas, items, stats,[n]money, or even your name.[e]

[dlg GENERIC_HELP_95]
[s]Choose a type of battle[n]to start, then begin[n]the fight![e]

[dlg GENERIC_HELP_96]
[s]Clip through walls and explore[n]out of bounds areas. Hold[n]Square to change axis.[e]

[dlg GENERIC_HELP_97]
[s]Select a BGM ID to[n]play back an audio track.[e]

[dlg GENERIC_HELP_98]
[s]Enter the ID of a field pack[n]to warp to that map.[e]

[dlg GENERIC_HELP_99]
[s]Enter the ID of an event pack[n]to start the event.[e]

[dlg GENERIC_HELP_100]
[s]Change the camera's position,[n]rotation, and field of view.[e]

[dlg GENERIC_HELP_101]
[s]Spawn NPC models and[n]preview their animations.[e]

[dlg GENERIC_HELP_102]
[s]Change various values[n]in the game's memory.[e]

[dlg GENERIC_HELP_103]
[s]Set a date and time and[n]travel directly to it.[e]

[dlg GENERIC_HELP_104]
[s]Test the dialogue cutins for[n]party members.[e]

[dlg GENERIC_HELP_105]
[s]Test the character placement[n]in the game's font.[e]

[dlg GENERIC_HELP_106]
[s]Spawn particles and[n]manipulate their properties.[e]

[dlg GENERIC_HELP_107]
[s]Change ENV and Fog values.[e]

[dlg GENERIC_HELP_108]
[s]Load any of the public shops[n]and test purchases.[e]

[dlg GENERIC_HELP_109]
[s]Send any text chat conversation[n]to your phone.[e]

[dlg GENERIC_HELP_110]
[s]Show some info about the[n]development of this mod.[e]

[dlg PlayerMenuName]
Player Options[w][e]

[sel PlayerMenu]
[s]Personas[f 4 26 0 113][e]
[s]Social Stats[f 4 26 1 114][e]
[s]Items[f 4 26 2 115][e]
[s]Set Confidant Rank[f 4 26 3 116][e]
[s]Set Protag Name[f 4 26 4 117][e]
[s]Set Team Name[f 4 26 5 118][e]
[s]Animation Test[f 4 26 6 119][e]
[s]Set Scale[f 4 26 7 120][e]
[s]Attach Item Model[f 4 26 8 121][e]
[s]Max Money[f 4 26 9 122][e]

[dlg GENERIC_HELP_113]
[s]Add or remove your Personas, or[n]give you or your party[n]members new Skills.[e]

[dlg GENERIC_HELP_114]
[s]Add points to your Knowledge,[n]Charm, Proficiency, Guts[n]or Kindness.[e]

[dlg GENERIC_HELP_115]
[s]Give yourself a desired amount of[n]any consumables, weapons, armor,[n]costumes, or even key items.[e]

[dlg GENERIC_HELP_116]
[s]Select a Confidant and set your[n]current rank with their Arcana.[e]

[dlg GENERIC_HELP_117]
[s]Rename the protagonist at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_118]
[s]Change the group name of the[n]Phantom Thieves at any[n]point in the game.[n][e]

[dlg GENERIC_HELP_119]
[s]Select one of the protagonist's[n]Field GAP files and view[n]its animations.[e]

[dlg GENERIC_HELP_120]
[s]Change the size of the[n]selected model.[e]

[dlg GENERIC_HELP_121]
[s]Enter an item's model ID[n]to attach it to the[n]protagonist's right hand.[e]

[dlg GENERIC_HELP_122]
[s]Adds 9,999,999 yen to your[n]wallet.[e]

[dlg ItemMenuName]
Select Item Type...[w][e]

[sel ItemMenu]
Consumables[f 4 26 0 125][e]
Accessories[f 4 26 1 126][e]
Key Items[f 4 26 2 127][e]
Ranged Weapons[f 4 26 3 128][e]
Melee Weapons[f 4 26 4 129][e]
Outfits[f 4 26 5 130][e]
Armor[f 4 26 6 131][e]
Materials[f 4 26 7 132][e]
Skill Cards[f 4 26 8 133][e]

[dlg GENERIC_HELP_125]
[s]Items that recover HP & SP,[n]relieve status ailments, or[n]provide buffs or debuffs.[e]

[dlg GENERIC_HELP_126]
[s]Items that you can equip to your[n]party members for stat[n]enhancements.[e]

[dlg GENERIC_HELP_127]
[s]Passive items that are acquired[n]throughout the story.[e]

[dlg GENERIC_HELP_128]
[s]Arms that can be equipped to[n]fire bullets during battle.[e]

[dlg GENERIC_HELP_129]
[s]Weapons used for basic physical[n]attacks during battle.[e]

[dlg GENERIC_HELP_130]
[s]Equippable appearance changes[n]for party members that modify[n]their model in the Metaverse.[e]

[dlg GENERIC_HELP_131]
[s]Equippable items that can boost[n]defense or provide other benefits.[e]

[dlg GENERIC_HELP_132]
[s]Items that can be sold to Iwai[n]or used to create tools.[e]

[dlg GENERIC_HELP_133]
[s]Items that can be used to assign[n]Skills to one of your Personas.[e]


[dlg CommuMenuName]
Select Confidant...[w][e]

[sel CommuMenu]
Igor[f 4 26 0 136][e]
[f 2 4 3][f 4 26 1 137][e]
[f 2 4 6][f 4 26 2 138][e]
[f 2 4 7][f 4 26 3 139][e]
[f 2 4 5][f 4 26 4 140][e]
[f 2 4 16][f 4 26 5 141][e]
[f 2 4 4][f 4 26 6 142][e]
[f 2 4 2][f 4 26 7 143][e]
[f 2 4 9][f 4 26 8 144][e]
[f 2 4 8][f 4 26 9 145][e]
[f 2 4 17][f 4 26 10 146][e]
[f 2 4 19] and [f 2 4 18][f 4 26 11 147][e]
[f 2 4 20][f 4 26 12 148][e]
[f 2 4 21][f 4 26 13 149][e]
[f 2 4 22][f 4 26 14 150][e]
[f 2 4 23][f 4 26 15 151][e]
[f 2 4 24][f 4 26 16 152][e]
[f 2 4 25][f 4 26 17 153][e]
[f 2 4 26][f 4 26 18 154][e]
[f 2 4 27][f 4 26 19 155][e]
[f 2 4 28][f 4 26 20 156][e]
Kasumi[f 4 26 33 157][e]
Maruki[f 4 26 35 158][e]
Sumire[f 4 26 36 159][e]

[dlg GENERIC_HELP_136]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fool[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_137]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Magician[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_138]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Priestess[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_139]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Empress[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_140]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Emperor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_141]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Heirophant[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_142]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Lovers[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_143]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Chariot[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_144]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Justice[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_145]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hermit[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_146]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Fortune[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_147]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Strength[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_148]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Hanged Man[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_149]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Death[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_150]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Temperance[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_151]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Devil[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_152]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Tower[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_153]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Star[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_154]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Moon[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_155]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Sun[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_156]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Judgement[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_157]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Faith[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_158]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Councillor[clr 0][n]Arcana.[e]

[dlg GENERIC_HELP_159]
[s]Set the desired rank for[n]the Confidant of the [clr 9]Faith[clr 0][n]Arcana.[e]

[dlg UNUSED_HELP_59]
[s]Set the desired rank for[n]the Confidant of the [clr 9]World[clr 0][n]Arcana.[e]

[dlg StatsMenuName]
Select Stat Type...[w][e]

[sel StatsMenu]
Knowledge[f 4 26 0 163][e]
Charm[f 4 26 1 164][e]
Proficiency[f 4 26 2 165][e]
Guts[f 4 26 3 166][e]
Kindness[f 4 26 4 167][e]

[dlg GENERIC_HELP_163]
[s]Increase your [clr 26]Knowledge[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_164]
[s]Increase your [clr 26]Charm[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_165]
[s]Increase your [clr 26]Proficiency[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_166]
[s]Increase your [clr 26]Guts[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg GENERIC_HELP_167]
[s]Increase your [clr 26]Kindness[clr 0] stat[n]by the specified number of[n]points.[e]

[dlg StatPrompt [Stats]]
Add how many points?[n](max. 2 digits, press Circle to end)[w][e]

[dlg ItemPrompt [Items]]
Enter the item ID you want.[n](max. 4 digits, press Circle to end)[w][e]

[dlg ItemPrompt2 [Items]]
Enter how many items you want.[n](max. 2 digits, press Circle to end)[w][e]

[dlg CmmDialog [Confidant Rank]]
Enter the Confidant's Arcana ID.[n](max. 2 digits, press Circle to end)[w][e]

[dlg CmmDialog2 [Confidant Rank]]
Enter the desired Confidant rank.[w][e]


[dlg AnimMenuName]
Player Animation[w][e]

[sel AnimMenu]
Field Animation Test[e]
Morgana Out of Bag[e]
Morgana In Bag[e]
Show Bag[e]
Hide Bag[e]
Umbrella On[e]
Umbrella Off[e]

[dlg GAPMenuName]
GAP Playback[w][e]

[sel GAPMenu]
Set GAP ID[f 4 26 0 177][e]
Set GAP Index[f 4 26 1 178][e]
Toggle Loop[f 4 26 2 179][e]
Set Speed[f 4 26 3 180][e]
Set Time[f 4 26 4 181][e]
Playback animation[f 4 26 5 182][e]

[dlg GENERIC_HELP_177]
[s]Input the filename of[n]a [clr 9]field GAP file for[clr 0][n]this character. (Starts with [clr 9]af[clr 0])[e]

[dlg GENERIC_HELP_178]
[s]Input the index of the[n]animation from the [clr 26]GAP[clr 0][n]that you want to view.[e]

[dlg GENERIC_HELP_179]
[s]Decide whether you want[n]the animation to repeat or not[n]when it's finished.[e]

[dlg GENERIC_HELP_180]
[s]Decide the playback speed[n]of the animation.[e]

[dlg GENERIC_HELP_181]
[s]Decide how many seconds you[n]would like to play the[n]animation for.[e]

[dlg GENERIC_HELP_182]
[s]Execute the animation playback[n][clr 9]after the above settings[clr 0][n]have been completed.[e]

[dlg ScalePrompt [Scale Model]]
Set the character's model scale.[n](press Circle to end)[n]Default is 10.[w][e]


[dlg CameraMenuName]
Camera Options[w][e]

[sel CameraMenu]
Reposition Camera[f 4 26 0 186][e]
Adjust FOV[f 4 26 1 187][e]
Adjust Zoom[f 4 26 2 188][e]
Rotate Camera[f 4 26 3 189][e]
Unlock Camera[f 4 26 4 190][e]
Lock Camera[f 4 26 5 191][e]
Disable Camera Shake[f 4 26 6 192][e]

[dlg GENERIC_HELP_186]
[s]Move the camera along the X, Y[n]or Z axis. Hold Square to change[n]the axis.[e]

[dlg GENERIC_HELP_187]
[s]Adjust the camera's[n]Field of View.[e]

[dlg GENERIC_HELP_188]
[s]Zoom the camera in[n]and out.[e]

[dlg GENERIC_HELP_189]
[s]Change the orientation of the[n]camera with the D-pad.[e]

[dlg GENERIC_HELP_190]
[s]Make the camera follow the player[n]again if previously locked.[e]

[dlg GENERIC_HELP_191]
[s]Makes the camera stationary,[n]which is required to modify it.[e]

[sel OneThruTen]
1[e]
2[e]
3[e]
4[e]
5[e]
6[e]
7[e]
8[e]
9[e]
10[e]

[dlg CalendarMenuName]
Calendar Options[w][e]

[sel CalendarMenu]
Set Next Day[f 4 26 0 195][e]
Call Calendar[f 4 26 1 196][e]
Set Weather[f 4 26 2 197][e]
Loop Current Day[f 4 26 3 198][e]

[dlg GENERIC_HELP_195]
[s]Choose the day and month[n]to warp to.[e]

[dlg GENERIC_HELP_196]
[s]End the current day and warp[n]to the next specified day.[e]

[dlg GENERIC_HELP_197]
[s]Change the current weather[n]condition value. Weather should[n]change after reloading map.[e]

[dlg GENERIC_HELP_198]
[s]Sets the current time[n]of day to be next after[n]ending the current day.[e]

[dlg CalendarPrompt[Calendar]]
Choose what month to start in.[n](press Circle to end)[w][e]

[dlg CalendarPrompt2 [Calendar]]
Choose what day to start on.[n](max. 2 digits, press Circle to end)[w][e]

[dlg EventDlg [Event Select]]
Choose the first 3 digits of
[n]the event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg EventDlg2 [Event Select]]
Choose the last 3 digits of
[n]the event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg KfEventDlg [KeyFree Event Select]]
Choose the first 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg KfEventDlg2 [KeyFree Event Select]]
Choose the last 3 digits of
[n]the KeyFree event to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg FieldDlg [Field Select]]
Choose the first 3 digits of
[n]the field to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg FieldDlg2 [Field Select]]
Choose the last 3 digits of
[n]the field to load.[n](max. 3 digits, press Circle to end)[w][e]

[dlg SpawnMenuName]
NPC Options[w][e]

[sel SpawnMenu]
Spawn Model[f 4 26 0 209][e]
Animate Model[f 4 26 1 210][e]
Set Model Scale[f 4 26 2 211][e]
Attach Item Model[f 4 26 3 212][e]
Spawn Object Model[f 4 26 4 213][e]

[dlg GENERIC_HELP_209]
[s]Input a [clr 9]GMD filename[clr 0][n]to spawn a character model from.[e]

[dlg GENERIC_HELP_210]
[s]Apply field animations[n]to the last NPC you spawned.[e]

[dlg GENERIC_HELP_211]
[s]Set the scale of the[n]NPC model.[e]

[dlg GENERIC_HELP_212]
[s]Input a [clr 9]GMD filename[clr 0][n]to attach to the NPC.[e]

[dlg GENERIC_HELP_213]
[s]Input a [clr 9]GMD filename[clr 0][n]of an object to spawn.[e]

[dlg PersonaMenuName]
Persona Options[w][e]

[sel PersonaMenu]
Add Persona[f 4 26 0 216][e]
Delete Personas[f 4 26 1 217][e]
Add Skill[f 4 26 2 218][e]
Unlock Full Compendium[f 4 26 3 219][e]
Evolve Persona[f 4 26 4 220][e]

[dlg GENERIC_HELP_216]
[s]Input a Persona's name or ID[n]to add it to your stock.[e]

[dlg GENERIC_HELP_217]
[s]Permanently remove all Personas[n]from your current stock.[e]

[dlg GENERIC_HELP_218]
[s]Choose a party member and the[n]name or ID of a Skill to add[n]to their current Persona.[e]

[dlg GENERIC_HELP_219]
[s]Register every Persona in[n]the game by filling your[n]stock with them all.[e]

[dlg GENERIC_HELP_220]
[s]Evolve a party member's Persona[n]into its Ultimate form.[e]


[dlg UnitMenuName]
Select Party Member[w][e]

[sel UnitSelect]
[f 2 4 1][e]
[f 2 4 2][e]
[f 2 4 3][e]
[f 2 4 4][e]
[f 2 4 5][e]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 8][e]
[f 2 4 9][e]
Yoshizawa[e]

[sel UnitSelect2]
[f 2 4 2][e]
[f 2 4 3][e]
[f 2 4 4][e]
[f 2 4 5][e]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 8][e]
[f 2 4 9][e]
Yoshizawa[e]

[dlg PersonaDelPrompt [Delete Personas]]
This will permanently remove all 
[n]Personas in your stock. Are you sure?[w][e]

[dlg UnitPrompt [Add Skill]]
Choose a character to add a skill to
[n]their currently equipped Persona.[w][e]

[dlg SkillPrompt [Add Skill]]
Enter the ID of the skill to add.
[n](max. 4 digits, press Circle to end)[w][e]

[dlg PersonaAddPrompt [Add Persona]]
Input the ID of the Persona to add.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg NPCPrompt [Model Select]]
Set the first (4 digits) of the NPC
[n]filename to load. (Press Circle to end)[w][e]

[dlg NPCPrompt2 [Model Select]]
Set the next (3 digits) of the NPC
[n]model filename to load. (Press Circle to end)[w][e]

[dlg NPCPrompt3 [Model Select]]
Set the last (2 digits) of the NPC
[n]model filename to load. (Press Circle to end)[w][e]

[dlg GapPrompt [Animation Test]]
Select the GAP ID.
[n](max. 3 digits, press Circle to end)[w][e]

[dlg GapPrompt2 [Animation Test]]
Select which animation to play.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt3 [Animation Test]]
Select whether to loop or not.[w][e]

[dlg GapPrompt4 [Animation Test]]
Select the third parameter.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt5 [Animation Test]]
Select the animation speed. Default is 10.
[n](max. 2 digits, press Circle to end)[w][e]

[dlg GapPrompt6 [Animation Test]]
Select the number of seconds to play.[w][e]

[dlg CameraPrompt [Camera Mode]]
Use the D-Pad to manipulate the camera.
[n]Press Triangle to quit.
[n](Camera must be locked first!)[w][e]

[dlg SelectBgmDialog [Ultimate DJ TGE]]
Select a bgm to play.[w][e]

[dlg FlagMenuName]
Flag Options[w][e]

[sel FlagMenu]
HUD Display[f 4 26 0 241][e]
Add Party Members[f 4 26 1 242][e]
Remove Party Members[f 4 26 2 243][e]
Enable Party Editing[f 4 26 3 244][e]
Unlock All Persona Slots[f 4 26 4 245][e]
Add Overworld Follower[f 4 26 5 246][e]
Navigator[f 4 26 6 247][e]
Change Romance Route[f 4 26 7 248][e]
Room Editor[f 4 26 8 249][e]
Manual Input[f 4 26 9 250][e]
Print Enabled Flags[f 4 26 10 251][e]
Mass Flag Editor[f 4 26 11 252][e]

[dlg GENERIC_HELP_241]
[s]Show or hide the user interface[n]elements, such as the date, time,[n]and mission list.[e]

[dlg GENERIC_HELP_242]
[s]Make a Persona user available to[n]add to your party.[e]

[dlg GENERIC_HELP_243]
[s]Revoke a Persona user's[n]availability to be added[n]to your party.[e]

[dlg GENERIC_HELP_244]
[s]Allow choosing your own[n]party members from the Stats[n]menu in the pause menu.[e]

[dlg GENERIC_HELP_245]
[s]Unlocks all 12 Persona slots.[e]

[dlg GENERIC_HELP_246]
[s]Enable or disable party[n]members following you[n]in the overworld.[e]

[dlg GENERIC_HELP_247]
[s]Change which character[n]currently serves as the Navigator.[e]

[dlg GENERIC_HELP_248]
[s]Start or end a relationship with[n]a female Confidant.[e]

[dlg GENERIC_HELP_249]
[s]Modify the state of the[n]protagonist's bedroom in[n]the Leblanc attic.[e]

[dlg GENERIC_HELP_250]
[s]Enter a 5-digit decimal value[n]of a bit to either[n]enable or disable it.[e]

[dlg GENERIC_HELP_251]
[s]Print all currently enabled[n]bit flag values to the[n]TTY log.[e]

[dlg GENERIC_HELP_252]
[s]Manipulate a selected[n]range of bit flags to[n]toggle or print.[e]

[dlg FieldMenuName]
Field Select[e]

[sel FieldMenu]
Enter Field ID[f 4 26 0 255][e]
Select by name[f 4 26 1 256][e]
Load Field[f 4 26 2 257][e]
Reload Current Field[f 4 26 3 258][e]

[dlg GENERIC_HELP_255]
[s]Input the 6 digits of a[n][clr 9]field pack's[clr 0] filename[n](found in ps3.cpk/field)[e]

[dlg GENERIC_HELP_256]
[s]Select a field by name[e]

[dlg GENERIC_HELP_257]
[s]Attempt to load the selected[n]field. [clr 9]WARNING: Some fields may[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_258]
[s]Reload the field that[n]you're currently on.[e]

[dlg EventMenuName]
Event Select[e]

[sel EventMenu]
Enter Event ID[f 4 26 0 261][e]
Load Event[f 4 26 1 262][e]
Enter KeyFree Event ID[f 4 26 2 263][e]
Load KeyFree Event[f 4 26 3 264][e]

[dlg GENERIC_HELP_261]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in data.cpk/event)[e]

[dlg GENERIC_HELP_262]
[s]Attempt to load the selected[n]event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg GENERIC_HELP_263]
[s]Input the 6 digits of a[n][clr 9]event pack's[clr 0] filename[n](found in ps3.cpk/field).[clr 0][e]

[dlg GENERIC_HELP_264]
[s]Attempt to load the selected[n]KeyFree event. [clr 9]WARNING: Some events may[n]softlock the game.[clr 0][e]

[dlg NaviMenuName]
Select Navigator[w][e]

[sel NaviMenu]
[f 2 4 3][e]
[f 2 4 8][e]
None[e]

[sel DateDisplayDlg]
Enable[e]
Disable[e]

[dlg LoveMenuName]
Select Relationship[w][e]

[sel LoveMenu]
[f 2 4 6][e]
[f 2 4 7][e]
[f 2 4 4][e]
[f 2 4 8][e]
[f 2 4 17][e]
[f 2 4 21][e]
[f 2 4 22][e]
[f 2 4 23][e]
[f 2 4 25][e]

[dlg AboutDlg[About this menu]]
Created by [clr 1]TGE[clr 0], [clr 6]ShrineFox[clr 0] and [clr 15]CaptainSwag101[clr 0]
[n]using TGE's [clr 9]AtlusScriptCompiler[clr 0] tool. Visit
[n]amicitia.github.io to learn more![w][e]

[sel RoomEdit]
Furniture[e]
Collectibles[e]
Cleanliness[e]

[sel FurnEdit]
Plant[e]
Sayuri[e]
DVD Player[e]
Game Console[e]
Old TV Set[e]
Radio[e]
Cat Bed[e]
UFO Game Prizes...[e]

[sel CollEdit]
Swan Boat[e]
Ramen[e]
Pennant[e]
Statue[e]
Sky Tree[e]
Big Hera[e]
Shumai[e]
Fusen[e]
I Love[e]
Idol[e]
More...[e]

[sel CollEdit2]
Seiza[e]
Syogi[e]
Hero[e]
Hamaya[e]
Jyainyan[e]
Sushi[e]
Choco[e]
Kumade[e]
Prev...[e]

[sel CleanEdit]
Bookshelf[e]
Workbench[e]
Visitor Table[e]
Training Chair[e]
Winter Heater[e]
Laptop[e]

[dlg MonthMenuName]
Select a Month[e]

[sel MonthMenu]
January[e]
February[e]
March[e]
April[e]
May[e]
June[e]
July[e]
August[e]
September[e]
October[e]
November[e]
December[e]

[dlg CalendarError]
Invalid day selected.[n]
Please try again.[w][e]

[dlg CalendarBackwardsError]
You can only go back one day at a time.[w][e]

[dlg SelectBossName]
Boss Event Select[w][e]

[sel Palace1]
Battle Scenario 1[e]
Battle with Morgana[e]
Battle Scenario 2[e]
Battle Scenario 3[e]
Sub Battle 1[e]
Sub Battle 2[e]
Gun Tutorial[e]
Hold Up Tutorial[e]
All Out Attack Tutorial[e]
Persona Recruit Tutorial[e]
Mini Boss 1[e]
Mini Boss 2[e]
Shadow Kamoshida[e]

[sel Palace2]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Battle Scenario[e]
Shadow Madarame[e]

[sel Palace3]
Battle Scenario[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Mini Boss 5[e]
Shadow Kaneshiro[e]

[sel Palace4]
Bandit[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Wakaba[e]

[sel Palace5]
Cognitive Sugimura[e]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
Shadow Okumura[e]

[sel Palace6]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3 (05_B)[e]
Mini Boss 4 (05_BOSS)[e]
Akechi's First Battle[e]
Mini Boss (Dark Zone)[e]
Mini Boss (Camera Room)[e]
Mini Boss (Dice)[e]
Slot (ENYRY) Battle[e]
Escape Battle[e]
Shadow Sae[e]

[sel Palace7]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
Mini Boss 4[e]
First Target[e]
Second Target[e]
Third Target[e]
Fourth Target[e]
Fifth Target[e]
Akechi[e]
Shadow Shido[e]

[sel Palace8]
Mini Boss 1[e]
Mini Boss 2[e]
Mini Boss 3[e]
The Holy Grail[e]
The Twins[e]
Uriel[e]
Raphael[e]
Gabriel[e]
Michael[e]
Yaldabaoth[e]

[sel Misc1]
Prologue Battle[e]
QUEST_BATTLE[e]
Yusuke Co-op[e]
int_CLEAR[e]
ALERT_CLEAR_EX[e]
PALACE_CLEAR_SYS[e]
PALACE_CALL_CALENDAR[e]
Closest encounter to position[e]
D_ENCOUNT_START[e]
dungeon_return_calendar[e]
dungeon_return[e]
Next[e]

[sel Misc2]
dungeon_exit_time_set[e]
dungeon_start_format[e]
DUNGEON_START_SAVE[e]
result_counter_clear[e]
MVP_CHOICE (CRASH!)[e]
D_ENCOUNT_NO_GET[e]
Dummy[e]
Dummy[e]
Previous[e]

[dlg HudTest1]
HUD has been enabled.[w][e]

[dlg HudTest2]
HUD has been disabled.[w][e]

[dlg PersonaAdded]
The chosen Persona has been[n]added to your stock.[w][e]

[dlg PersonaDeleted]
All Personas have been deleted.[w][e]

[dlg WeatherChanged]
Weather has been changed.[w][e]

[dlg LoadCheckError]
Set the required parameters[n]before attempting to load![w][e]

[dlg WeatherMenuName]
Weather Select[w][e]

[sel WeatherMenu]
Sunny[e]
Rainy[e]
Cloudy[e]
Snow[e]
Rainy Season[e]
Typhoon Warning[e]
Sunny Pollen Warning[e]
Cloudy Pollen Warning[e]
Torrential Rain[e]
Sunny Heatwave/Hot Night[e]
Sunny Flu Season[e]
Cloudy Flu Season[e]

[dlg BattleTypeName]
Battle Type Select[w][e]

[sel BattleTypeMenu]
Regular Encounter[e]
Boss Encounter[e]
Event Battle[e]

[dlg EventBattleName]
Battle Type Select[w][e]

[sel PalaceMenu]
Castle[e]
Art Museum[e]
First World Bank[e]
Pyramid[e]
Space Station[e]
Casino[e]
Cruise Ship[e]
Mementos Depths[e]
Misc[e]

[dlg PalaceName]
Palace Select[e]

[sel EventBattleSelect]
Akechi[e]
Akechi Phase 2[e]
Holy Grail[e]
Yaldabaoth[e]
Velvet Twins[e]
MISC[e]

[dlg EncounterPrompt]
Set the number of the encounter[n]you want to fight (3 digits).[w][e]

[dlg ShopPrompt [Shop Test]]
Input the ID of the shop[n]you want to test (2 digits).[w][e]

[dlg ChatPrompt [Chat Test]]
Input the ID of the chat[n]you want to test (4 digits).[w][e]

[sel FlagMassEditor]
Disable all flags[e]
Enable all flags[e]
Swap enabled/disabled flags[e]
Toggle range of flags[e]
Clear Inherit Data[e]

[dlg PersonaAddSkillMenuName]
Persona Options[w][e]

[sel PersonaAddSkillMenu]
Add Skill[e]
Add Skill (Manual Input)[e]
Add Skill (Reserves)[e]

[dlg PersonaAddMenuName]
Persona Options[w][e]

[sel PersonaAddMenu]
Add Persona[e]
Add Persona (Manual Input)[e]
Add Persona (Reserves)[e]

[dlg BagShowHide]
The bag has been toggled.[n]To see the change, go to a new field[n]or reload the current one.[w][e]

[dlg GENERIC_HELP_314]
Removes the swaying effect[n]of the camera that's[n]used in dungeons.[w][e]

[dlg GENERIC_HELP_315]
Select an item's model ID to[n]spawn it and connect it to[n]the character's model.[w][e]

[dlg GENERIC_HELP_316]
Select a range of flags[n]to either enable or disable.[w][e]

[dlg ItemSpawnPrompt]
Enter the first half of the model's[n]ID from data.cpk/model/item.[n](Max 4 digits, press Circle to end).[w][e]

[dlg ItemSpawnPrompt2]
Enter the last half of the model's[n]ID from data.cpk/model/item.[n](Max 3 digits, press Circle to end).[w][e]

[dlg ObjectSpawnPrompt]
Enter the first half of the[n]model's ID from data.cpk/model/field_tex/object.[n](Max 3 digits, press Circle to end).[w][e]

[dlg ObjectSpawnPrompt2]
Enter the last half of the[n]model's ID from data.cpk/model/field_tex/object.[n](Max 3 digits, press Circle to end).[w][e]

[dlg FlagRangePrompt]
Enter the start of the[n]range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[dlg FlagRangePrompt2]
Enter the end of the[n]range to narrow down.[n](Max 4 digits, press Circle to end).[w][e]

[dlg GENERIC_HELP_323]
Unlocks all Personas in the[n]Compendium. [clr 9]This will delete all[n]Personas in your current stock![clr 0][w][e]

[dlg FontMenuName]
Font Test Options[w][e]

[sel FontTestMenu]
[s]Sample text[f 4 26 0 326][e]
[s]Uppercase[f 4 26 1 327][e]
[s]Lowercase[f 4 26 2 328][e]
[s]Symbols[f 4 26 3 329][e]
[s]All-in-One[f 4 26 4 330][e]

[dlg GENERIC_HELP_326]
[s]Print a sample sentence[n]for font testing.[e]

[dlg GENERIC_HELP_327]
[s]Print a text message with[n]uppercase letters.[e]

[dlg GENERIC_HELP_328]
[s]Print a text message with[n]lowercase letters.[e]

[dlg GENERIC_HELP_329]
[s]Print a text message with[n]numbers and special[n]characters.[e]

[dlg GENERIC_HELP_330]
[s]Print a text message with[n]all the characters.[e]

[dlg FontTest0[The Font Guy]]
[s]The quick brown fox jumps over[n]the lazy dog. 1234567890[n][w][e]

[dlg FontTest1[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]A B C D E F G H I J K L M N O P Q R S T U V W X Y Z[w][e]

[dlg FontTest2[The Font Guy]]
[s]abcdefghijklmnopqrstuvwxyz[n]a b c d e f g h i j k l m n o p q r s t u v w x y z[w][e]

[dlg FontTest3[The Font Guy]]
[s]1234567890-_.:,;|!"#$%&/()=?+*{}^\<>`~'@[n][w][e]

[dlg FontTest4[The Font Guy]]
[s]ABCDEFGHIJKLMNOPQRSTUVWXYZ[n]abcdefghijklmnopqrstuvwxyz[n]1234567890-_.:,;|!"#$%&/()=?+*{}^\<>`~'@[w][e]

[dlg PartyMemberCutinMenuName]
Party Member Cutin Test[w][e]

[sel PartyCharacterSelect]
[s][f 2 4 2][f 4 26 0 338][e]
[s][f 2 4 3][f 4 26 1 339][e]
[s][f 2 4 4][f 4 26 2 340][e]
[s][f 2 4 5][f 4 26 3 341][e]
[s][f 2 4 6][f 4 26 4 342][e]
[s][f 2 4 7][f 4 26 5 343][e]
[s][f 2 4 8][f 4 26 6 344][e]
[s][f 2 4 9][f 4 26 7 345][e]
[s]Villain [f 2 4 9][f 4 26 8 346][e]

[dlg GENERIC_HELP_338]
[s]Test the dialogue cutins[n]for [f 2 4 2].[e]

[dlg GENERIC_HELP_339]
[s]Test the dialogue cutins[n]for [f 2 4 3].[e]

[dlg GENERIC_HELP_340]
[s]Test the dialogue cutins[n]for [f 2 4 4].[e]

[dlg GENERIC_HELP_341]
[s]Test the dialogue cutins[n]for [f 2 4 5].[e]

[dlg GENERIC_HELP_342]
[s]Test the dialogue cutins[n]for [f 2 4 6].[e]

[dlg GENERIC_HELP_343]
[s]Test the dialogue cutins[n]for [f 2 4 7].[e]

[dlg GENERIC_HELP_344]
[s]Test the dialogue cutins[n]for [f 2 4 8].[e]

[dlg GENERIC_HELP_345]
[s]Test the dialogue cutins[n]for [f 2 4 9].[e]

[dlg GENERIC_HELP_346]
[s]Test the dialogue cutins[n]for Villain [f 2 4 9].[e]

[dlg ParticleMenuName]
Particle Menu[w][e]

[sel ParticleMenu]
[s]Automatic Particle Selection[f 4 26 0 349][e]
[s]Manual Particle Selection[f 4 26 1 350][e]
[s]Set Params to Default[f 4 26 2 351][e]
[s]Set Effect Size[f 4 26 3 352][e]
[s]Set Effect Speed[f 4 26 4 353][e]
[s]Set Effect Position[f 4 26 5 354][e]
[s]Set Effect Translucency[f 4 26 6 355][e]

[dlg GENERIC_HELP_349]
[s]Preview EPL's placed inside[n]'data.cpk\field\effect\bank'[n][clr 9]MUST BE NAMED fb###.EPL[n]OR THE GAME SOFTLOCKS![clr 0][e]

[dlg GENERIC_HELP_350]
[s]Select a 3-digit number from the[n]effect bank folder [clr 9](fb###.EPL)[n][clr 0]to preview.[e]

[dlg GENERIC_HELP_351]
[s]Reset all properties of[n]the current EPL.[n][e]

[dlg GENERIC_HELP_352]
[s]Set the Size[n]of the current EPL.[n][e]

[dlg GENERIC_HELP_353]
[s]Set the Speed[n]of the current EPL.[n][e]

[dlg GENERIC_HELP_354]
[s]Set the Position[n]of the current EPL to the player.[e]

[dlg GENERIC_HELP_355]
[s]Set the Opacity[n]of the current EPL.[n][e]

[dlg ScaleParticle]
Set the particles's scale.[n](press Circle to end)[n]Default is 10.[w][e]

[dlg SpeedParticle]
Set the particles's speed.[n](press Circle to end)[n]Default is 10.[w][e]

[dlg AlphaParticle]
Set the particles's opacity.[n](press Circle to end)[n]Default is 10.[w][e]

[sel EnviromentEditor]
[s]Set all Scenelights to White[f 4 26 0 360][e]
[s]Print Scenelights to TTY[f 4 26 1 361][e]
[s]Set Ambient Scenelight[f 4 26 2 362][e]
[s]Set Diffuse Scenelight[f 4 26 3 363][e]
[s]Set Specular Scenelight[f 4 26 4 364][e]
[s]Print Current Fog Params to TTY[f 4 26 5 365][e]
[s]Set Near Clip[f 4 26 6 366][e]
[s]Set Far Clip[f 4 26 7 367][e]
[s]Set Fog Hue[f 4 26 8 368][e]
[s]Set Fog Saturation[f 4 26 9 369][e]
[s]Set Fog Lightness[f 4 26 10 370][e]
[s]Set Fog Alpha[f 4 26 11 371][e]

[dlg GENERIC_HELP_360]
[s]Set all Scenelight data on[n]the current field to 255.[e]

[dlg GENERIC_HELP_361]
[s]Print all Scenelight data on[n]the current field to the TTY Log.[e]

[dlg GENERIC_HELP_362]
[s]Set the HSL Values for the[n]Ambient Scenelight.[e]

[dlg GENERIC_HELP_363]
[s]Set the HSL Values for the[n]Diffuse Scenelight.[e]

[dlg GENERIC_HELP_364]
[s]Set the HSL Values for the[n]Specular Scenelight.[e]

[dlg GENERIC_HELP_365]
[s]Print all fog params on[n]the current field to the TTY Log.[e]

[dlg GENERIC_HELP_366]
[s]Set the starting[n]location for the fog.[e]

[dlg GENERIC_HELP_367]
[s]Set the starting[n]radius for the fog.[e]

[dlg GENERIC_HELP_368]
[s]Set the current fog's Hue.[e]

[dlg GENERIC_HELP_369]
[s]Set the current fog's Saturation.[e]

[dlg GENERIC_HELP_370]
[s]Set the current fog's Lightness.[e]

[dlg GENERIC_HELP_371]
[s]Set the current fog's Opacity.[e]

[dlg HueDlg]
Set Hue to a 3 digit number. (Max 255)[w][e]

[dlg SatDlg]
Set Saturation to a 3 digit number. (Max 255)[w][e]

[dlg LumDlg]
Set Lightness to a 3 digit number. (Max 255)[w][e]

[dlg AlpDlg]
Set Opacity to a 3 digit number. (Max 255)[w][e]

[dlg NearClipDlg]
Set the fog's Near Clip[n](press Circle to end)[w][e]

[dlg FarClipDlg]
Set the fog's Far Clip[n](press Circle to end)[w][e]

[dlg FieldDlg3[Field Select]]
Choose the Entrance ID you'd like[n]to use (0 if unsure).[w][e]